# Generated by Django 4.0.6 on 2022-08-05 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_group_group_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageShared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_message', to='chat.message')),
            ],
        ),
    ]
