# Generated by Django 4.0.6 on 2022-08-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_message_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageShared',
        ),
    ]
