# Generated by Django 4.0.6 on 2022-08-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_delete_imageshared'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_status',
            field=models.BooleanField(default=False),
        ),
    ]
