# Generated by Django 4.0.6 on 2022-08-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_message_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_status',
        ),
    ]
