# Generated by Django 4.0.6 on 2022-08-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_remove_messagereplies_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereplies',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chat.message'),
        ),
    ]
