# Generated by Django 4.0.6 on 2022-08-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_messagereplies_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replied_message', to='chat.message')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='replied_to_message', to='chat.message')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageReplies',
        ),
    ]
