# Generated by Django 4.0.6 on 2022-08-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_messagereply_delete_messagereplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereply',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replied_to_message', to='chat.message'),
        ),
    ]
